Support vite and remove E2E_ENABLED
wongnai/rollup-plugin-data-qa pull request #2
Opened 2024-01-18 02:56 UTC by peetck

2024-01-18 04:24 UTC, ReiiYuki approved these changes

2024-01-18 04:29 UTC, ReiiYuki requested changes
After internal discussion, please allow e2e env

2024-01-19 11:22 UTC, nitpum requested changes

2024-01-19 11:22 UTC, nitpum commented on package.json
> +      },
types exports no need to split variants
```suggestion
      "types": "./index.d.ts",
```

2024-01-19 11:22 UTC, nitpum commented on package.json
> +      },
Or something like this instead. [ref](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-7.html#packagejson-exports-imports-and-self-referencing)
```ts
            "import": {
                // Where TypeScript will look.
                "types": "./types/esm/index.d.ts",
                // Where Node.js will look.
                "default": "./esm/index.js"
            },
            // Entry-point for `require("my-package") in CJS
            "require": {
                // Where TypeScript will look.
                "types": "./types/commonjs/index.d.cts",
                // Where Node.js will look.
                "default": "./commonjs/index.cjs"
            },
```

2024-01-22 04:13 UTC, ppipee commented
LGTM

2024-01-22 04:22 UTC, merged